/*
 * This file is generated by jOOQ.
*/
package com.example.jq.schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmText implements Serializable {

    private static final long serialVersionUID = -1491009218;

    private Short  filmId;
    private String title;
    private String description;

    public FilmText() {}

    public FilmText(FilmText value) {
        this.filmId = value.filmId;
        this.title = value.title;
        this.description = value.description;
    }

    public FilmText(
        Short  filmId,
        String title,
        String description
    ) {
        this.filmId = filmId;
        this.title = title;
        this.description = description;
    }

    public Short getFilmId() {
        return this.filmId;
    }

    public void setFilmId(Short filmId) {
        this.filmId = filmId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FilmText (");

        sb.append(filmId);
        sb.append(", ").append(title);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
