/*
 * This file is generated by jOOQ.
*/
package com.example.jq.schema.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staff implements Serializable {

    private static final long serialVersionUID = -1522282512;

    private Byte      staffId;
    private String    firstName;
    private String    lastName;
    private Short     addressId;
    private byte[]    picture;
    private String    email;
    private Byte      storeId;
    private Byte      active;
    private String    username;
    private String    password;
    private Timestamp lastUpdate;

    public Staff() {}

    public Staff(Staff value) {
        this.staffId = value.staffId;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.addressId = value.addressId;
        this.picture = value.picture;
        this.email = value.email;
        this.storeId = value.storeId;
        this.active = value.active;
        this.username = value.username;
        this.password = value.password;
        this.lastUpdate = value.lastUpdate;
    }

    public Staff(
        Byte      staffId,
        String    firstName,
        String    lastName,
        Short     addressId,
        byte[]    picture,
        String    email,
        Byte      storeId,
        Byte      active,
        String    username,
        String    password,
        Timestamp lastUpdate
    ) {
        this.staffId = staffId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.addressId = addressId;
        this.picture = picture;
        this.email = email;
        this.storeId = storeId;
        this.active = active;
        this.username = username;
        this.password = password;
        this.lastUpdate = lastUpdate;
    }

    public Byte getStaffId() {
        return this.staffId;
    }

    public void setStaffId(Byte staffId) {
        this.staffId = staffId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Short getAddressId() {
        return this.addressId;
    }

    public void setAddressId(Short addressId) {
        this.addressId = addressId;
    }

    public byte[] getPicture() {
        return this.picture;
    }

    public void setPicture(byte... picture) {
        this.picture = picture;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Byte getStoreId() {
        return this.storeId;
    }

    public void setStoreId(Byte storeId) {
        this.storeId = storeId;
    }

    public Byte getActive() {
        return this.active;
    }

    public void setActive(Byte active) {
        this.active = active;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Staff (");

        sb.append(staffId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(addressId);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(email);
        sb.append(", ").append(storeId);
        sb.append(", ").append(active);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
