server:
    port: 8080
spring:
  application:
    name: jq
  jooq:
    sql-dialect: mysql_5_7
  datasource:
    name: datasource
    url: jdbc:mysql://localhost:3306/sakila2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      max-lifetime: 1800000
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  file: classpath:logback.xml