/*
 * This file is generated by jOOQ.
*/
package com.example.jq.sakila.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorInfo implements Serializable {

    private static final long serialVersionUID = 872509309;

    private Short  actorId;
    private String firstName;
    private String lastName;
    private String filmInfo;

    public ActorInfo() {}

    public ActorInfo(ActorInfo value) {
        this.actorId = value.actorId;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.filmInfo = value.filmInfo;
    }

    public ActorInfo(
        Short  actorId,
        String firstName,
        String lastName,
        String filmInfo
    ) {
        this.actorId = actorId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.filmInfo = filmInfo;
    }

    public Short getActorId() {
        return this.actorId;
    }

    public void setActorId(Short actorId) {
        this.actorId = actorId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFilmInfo() {
        return this.filmInfo;
    }

    public void setFilmInfo(String filmInfo) {
        this.filmInfo = filmInfo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActorInfo (");

        sb.append(actorId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(filmInfo);

        sb.append(")");
        return sb.toString();
    }
}
