/*
 * This file is generated by jOOQ.
*/
package com.example.jq.sakila.tables.pojos;


import com.example.jq.sakila.enums.NicerButSlowerFilmListRating;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NicerButSlowerFilmList implements Serializable {

    private static final long serialVersionUID = 803181321;

    private Short                        fid;
    private String                       title;
    private String                       description;
    private String                       category;
    private BigDecimal                   price;
    private Short                        length;
    private NicerButSlowerFilmListRating rating;
    private String                       actors;

    public NicerButSlowerFilmList() {}

    public NicerButSlowerFilmList(NicerButSlowerFilmList value) {
        this.fid = value.fid;
        this.title = value.title;
        this.description = value.description;
        this.category = value.category;
        this.price = value.price;
        this.length = value.length;
        this.rating = value.rating;
        this.actors = value.actors;
    }

    public NicerButSlowerFilmList(
        Short                        fid,
        String                       title,
        String                       description,
        String                       category,
        BigDecimal                   price,
        Short                        length,
        NicerButSlowerFilmListRating rating,
        String                       actors
    ) {
        this.fid = fid;
        this.title = title;
        this.description = description;
        this.category = category;
        this.price = price;
        this.length = length;
        this.rating = rating;
        this.actors = actors;
    }

    public Short getFid() {
        return this.fid;
    }

    public void setFid(Short fid) {
        this.fid = fid;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Short getLength() {
        return this.length;
    }

    public void setLength(Short length) {
        this.length = length;
    }

    public NicerButSlowerFilmListRating getRating() {
        return this.rating;
    }

    public void setRating(NicerButSlowerFilmListRating rating) {
        this.rating = rating;
    }

    public String getActors() {
        return this.actors;
    }

    public void setActors(String actors) {
        this.actors = actors;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NicerButSlowerFilmList (");

        sb.append(fid);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(category);
        sb.append(", ").append(price);
        sb.append(", ").append(length);
        sb.append(", ").append(rating);
        sb.append(", ").append(actors);

        sb.append(")");
        return sb.toString();
    }
}
