/*
 * This file is generated by jOOQ.
*/
package com.example.jq.schema;


import com.example.jq.schema.tables.Actor;
import com.example.jq.schema.tables.ActorInfo;
import com.example.jq.schema.tables.Address;
import com.example.jq.schema.tables.Category;
import com.example.jq.schema.tables.City;
import com.example.jq.schema.tables.Country;
import com.example.jq.schema.tables.Customer;
import com.example.jq.schema.tables.CustomerList;
import com.example.jq.schema.tables.Film;
import com.example.jq.schema.tables.FilmActor;
import com.example.jq.schema.tables.FilmCategory;
import com.example.jq.schema.tables.FilmList;
import com.example.jq.schema.tables.FilmText;
import com.example.jq.schema.tables.Inventory;
import com.example.jq.schema.tables.Language;
import com.example.jq.schema.tables.NicerButSlowerFilmList;
import com.example.jq.schema.tables.Payment;
import com.example.jq.schema.tables.Rental;
import com.example.jq.schema.tables.SalesByFilmCategory;
import com.example.jq.schema.tables.SalesByStore;
import com.example.jq.schema.tables.Staff;
import com.example.jq.schema.tables.StaffList;
import com.example.jq.schema.tables.Store;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sakila extends SchemaImpl {

    private static final long serialVersionUID = 597716825;

    /**
     * The reference instance of <code>sakila</code>
     */
    public static final Sakila SAKILA = new Sakila();

    /**
     * The table <code>sakila.actor</code>.
     */
    public final Actor ACTOR = com.example.jq.schema.tables.Actor.ACTOR;

    /**
     * VIEW
     */
    public final ActorInfo ACTOR_INFO = com.example.jq.schema.tables.ActorInfo.ACTOR_INFO;

    /**
     * The table <code>sakila.address</code>.
     */
    public final Address ADDRESS = com.example.jq.schema.tables.Address.ADDRESS;

    /**
     * The table <code>sakila.category</code>.
     */
    public final Category CATEGORY = com.example.jq.schema.tables.Category.CATEGORY;

    /**
     * The table <code>sakila.city</code>.
     */
    public final City CITY = com.example.jq.schema.tables.City.CITY;

    /**
     * The table <code>sakila.country</code>.
     */
    public final Country COUNTRY = com.example.jq.schema.tables.Country.COUNTRY;

    /**
     * The table <code>sakila.customer</code>.
     */
    public final Customer CUSTOMER = com.example.jq.schema.tables.Customer.CUSTOMER;

    /**
     * VIEW
     */
    public final CustomerList CUSTOMER_LIST = com.example.jq.schema.tables.CustomerList.CUSTOMER_LIST;

    /**
     * The table <code>sakila.film</code>.
     */
    public final Film FILM = com.example.jq.schema.tables.Film.FILM;

    /**
     * The table <code>sakila.film_actor</code>.
     */
    public final FilmActor FILM_ACTOR = com.example.jq.schema.tables.FilmActor.FILM_ACTOR;

    /**
     * The table <code>sakila.film_category</code>.
     */
    public final FilmCategory FILM_CATEGORY = com.example.jq.schema.tables.FilmCategory.FILM_CATEGORY;

    /**
     * VIEW
     */
    public final FilmList FILM_LIST = com.example.jq.schema.tables.FilmList.FILM_LIST;

    /**
     * The table <code>sakila.film_text</code>.
     */
    public final FilmText FILM_TEXT = com.example.jq.schema.tables.FilmText.FILM_TEXT;

    /**
     * The table <code>sakila.inventory</code>.
     */
    public final Inventory INVENTORY = com.example.jq.schema.tables.Inventory.INVENTORY;

    /**
     * The table <code>sakila.language</code>.
     */
    public final Language LANGUAGE = com.example.jq.schema.tables.Language.LANGUAGE;

    /**
     * VIEW
     */
    public final NicerButSlowerFilmList NICER_BUT_SLOWER_FILM_LIST = com.example.jq.schema.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST;

    /**
     * The table <code>sakila.payment</code>.
     */
    public final Payment PAYMENT = com.example.jq.schema.tables.Payment.PAYMENT;

    /**
     * The table <code>sakila.rental</code>.
     */
    public final Rental RENTAL = com.example.jq.schema.tables.Rental.RENTAL;

    /**
     * VIEW
     */
    public final SalesByFilmCategory SALES_BY_FILM_CATEGORY = com.example.jq.schema.tables.SalesByFilmCategory.SALES_BY_FILM_CATEGORY;

    /**
     * VIEW
     */
    public final SalesByStore SALES_BY_STORE = com.example.jq.schema.tables.SalesByStore.SALES_BY_STORE;

    /**
     * The table <code>sakila.staff</code>.
     */
    public final Staff STAFF = com.example.jq.schema.tables.Staff.STAFF;

    /**
     * VIEW
     */
    public final StaffList STAFF_LIST = com.example.jq.schema.tables.StaffList.STAFF_LIST;

    /**
     * The table <code>sakila.store</code>.
     */
    public final Store STORE = com.example.jq.schema.tables.Store.STORE;

    /**
     * No further instances allowed
     */
    private Sakila() {
        super("sakila", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Actor.ACTOR,
            ActorInfo.ACTOR_INFO,
            Address.ADDRESS,
            Category.CATEGORY,
            City.CITY,
            Country.COUNTRY,
            Customer.CUSTOMER,
            CustomerList.CUSTOMER_LIST,
            Film.FILM,
            FilmActor.FILM_ACTOR,
            FilmCategory.FILM_CATEGORY,
            FilmList.FILM_LIST,
            FilmText.FILM_TEXT,
            Inventory.INVENTORY,
            Language.LANGUAGE,
            NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST,
            Payment.PAYMENT,
            Rental.RENTAL,
            SalesByFilmCategory.SALES_BY_FILM_CATEGORY,
            SalesByStore.SALES_BY_STORE,
            Staff.STAFF,
            StaffList.STAFF_LIST,
            Store.STORE);
    }
}
